name: myapp
description: A fitness measurement tracking app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_secure_storage: ^9.0.0 # 修正缩进，与intl同级
  hive: ^2.2.3
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  rename: ^3.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"
  # remove_alpha_ios: true
  adaptive_icon_background: "#D4AF37"
  adaptive_icon_foreground: "assets/logo/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
